version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gym_saas_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gym_saas
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: gym_saas_redis_dev
    ports:
      - '6379:6379'

volumes:
  pgdata_dev:
